### ISSUE TITLE
Version 1.1.23 has empty package

### ISSUE THREAD

**Issue by khaosdoctor** [rwillians/express-rescue#8]
The published version 1.1.23 is empty on NPM: https://unpkg.com/express-rescue@1.1.23/dist/index.js

**Comment by rwillians** [comment]
Thanks @khaosdoctor 

Fixed on v1.1.25: https://unpkg.com/express-rescue@1.1.25/dist/index.js

**Comment by khaosdoctor** [comment]
Awesome! Thanks!
