### ISSUE TITLE
Missing type definitions on 1.1.25

### ISSUE THREAD

**Issue by khaosdoctor** [rwillians/express-rescue#9]
The newest version comes with the compiled file, however it does not have any type definition, which causes the following error on TypeScript files:

![image](https://user-images.githubusercontent.com/3200560/71550323-7575f580-29ac-11ea-91da-e35a0ae6651d.png)

This is the snapshot of the last version I used which has these definitions: https://unpkg.com/browse/express-rescue@1.1.20/dist/

As you can see [here](https://unpkg.com/browse/express-rescue@1.1.25/dist/) the 25 only has the `index.js` file.

**Comment by rwillians** [comment]
npm isn't so smart about which file extensions should be included within the package yet: https://github.com/rwillians/express-rescue/commit/4f8af604f5e65e02a95eb5dd3845849d30bf4a12

v1.1.26 has been published with type definitions: https://unpkg.com/browse/express-rescue@1.1.26/dist/
